// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW6XSsb-qt-QPjHWivlr2gkII2mTo8Voo',
    appId: '1:746631069079:web:ae5ac14926d4d8c42e98d2',
    messagingSenderId: '746631069079',
    projectId: 'flutter21-bd08a',
    authDomain: 'flutter21-bd08a.firebaseapp.com',
    databaseURL: 'https://flutter21-bd08a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter21-bd08a.appspot.com',
    measurementId: 'G-L2CF7CPE3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqwFRT7oD4QP5crXo0ixO09z-Fkv-se58',
    appId: '1:746631069079:android:f4df4d3f57d9505c2e98d2',
    messagingSenderId: '746631069079',
    projectId: 'flutter21-bd08a',
    databaseURL: 'https://flutter21-bd08a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter21-bd08a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcTQjYDfP7ZLuG8XGQqkoR4_4W-io-6NY',
    appId: '1:746631069079:ios:6206c3151bc1fdf12e98d2',
    messagingSenderId: '746631069079',
    projectId: 'flutter21-bd08a',
    databaseURL: 'https://flutter21-bd08a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter21-bd08a.appspot.com',
    iosClientId: '746631069079-uchk5ar7tnu0brie73beds530f4rp2hd.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverid01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcTQjYDfP7ZLuG8XGQqkoR4_4W-io-6NY',
    appId: '1:746631069079:ios:6206c3151bc1fdf12e98d2',
    messagingSenderId: '746631069079',
    projectId: 'flutter21-bd08a',
    databaseURL: 'https://flutter21-bd08a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter21-bd08a.appspot.com',
    iosClientId: '746631069079-uchk5ar7tnu0brie73beds530f4rp2hd.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverid01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW6XSsb-qt-QPjHWivlr2gkII2mTo8Voo',
    appId: '1:746631069079:web:f74159680dd7cdf52e98d2',
    messagingSenderId: '746631069079',
    projectId: 'flutter21-bd08a',
    authDomain: 'flutter21-bd08a.firebaseapp.com',
    databaseURL: 'https://flutter21-bd08a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter21-bd08a.appspot.com',
    measurementId: 'G-CPWLQ7PKMF',
  );
}
